src/blogproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from accounts.views import login_view, logout_view, register_view, activate

urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^confirm/$', TemplateView.as_view(template_name='confirm.html'), name='confirm'),
    url(r'^activate/(?P<id>\d+)/$', activate, name='activate'),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("posts.urls", namespace='posts')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.conf.urls import url

from .views import (
    post_list,
    post_detail,
    post_create,
    post_like,
    )

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^post/(?P<id>\d+)/like/$', post_like, name='like'),
    url(r'^post/(?P<id>\d+)/$', post_detail, name='detail'),
]

src/posts/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType


def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)
    

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            width_field="width_field", 
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        ordering = ["-timestamp"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"id": self.id})

    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


class Likes(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    post = models.ForeignKey(Post)

src/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "image"]

src/posts/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType

from comments.models import Comment
from comments.forms import CommentForm
from .forms import PostForm
from .models import Post, Likes


@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        return redirect(instance.get_absolute_url())
    context = {"form": form,
               "foreword": "Create new Post!",
               "inset": "Create",
               }
    return render(request, "post_form.html", context)


@login_required
def post_detail(request, id=None):
    instance = get_object_or_404(Post, id=id)
    count_likes = instance.likes_set.all().count()
    data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id,
    }

    comment_form = CommentForm(request.POST or None, initial=data)
    if comment_form.is_valid():
        cont_type = comment_form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=cont_type)
        obj_id = comment_form.cleaned_data.get("object_id")
        content_data = comment_form.cleaned_data.get("content")
        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
            content=content_data
            )

    content_type = ContentType.objects.get_for_model(Post)
    object_id = instance.id
    comments = Comment.objects.filter(content_type=content_type, object_id=object_id)

    paginator = Paginator(comments, 2)

    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "title": instance.title,
        "instance": instance,
        "queryset": queryset,
        "comment_form": comment_form,
        "count_likes": count_likes,
    }
    return render(request, "post_detail.html", context)


@login_required
def post_list(request):
    queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(user__first_name__icontains=query)|
            Q(user__country__icontains=query)|
            Q(user__city__icontains=query)
            ).distinct()
    paginator = Paginator(queryset_list, 2)
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {"object_list": queryset,
               "page_request_var": page_request_var,
               "foreword": "Welcome to DjangoApp!"
               }
    return render(request, "post_list.html", context)


@login_required
def post_like(request, id=None):
    instance = get_object_or_404(Post, id=id)
    new_like, created = Likes.objects.get_or_create(user=request.user, post=instance)
    if not created:
        new_like.delete()
    return redirect(instance.get_absolute_url())

src/blogproject/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blogproject</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"
          integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel='stylesheet' href='{% static "css/base.css" %}' />

    <style>
    </style>
</head>

<body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top nav-color">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'posts:list' %}">Blog</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'posts:list' %}">Home</a></li>
                    <li><a href="{% url 'posts:create' %}">Create post</a></li>
                </ul>

                <form method='GET' action='{% url "posts:list" %}' class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" name='q' class="form-control" placeholder="Search" value='{{ request.GET.q }}'>
                    </div>
                    <button type="submit" class="btn btn-default">Start</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                
                <ul class="nav navbar-nav">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Sign-out</a></li>
                {% else %}
                    <li><a href="{% url 'register' %}">Sign-up</a></li>
                    <li><a href="{% url 'login' %}">Sign-in</a></li>
                {% endif %}
                </ul>

                </ul>

            </div>

        </div>
    </nav>

    <div class='container margin-form'>
        {% block content %}{% endblock content %}
    </div>

</body>
</html>

src/blogproject/templates/confirm.html
<h1>Confirm your registration through email!</h1>

src/blogproject/templates/form.html
{% extends "base.html" %}

{% block content %}

<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ inset }}</h1>
    <hr/>

    <form method='POST' action=''>{% csrf_token %}
        <p>{{ form.as_p }}</p>
        <input type='submit' class='btn btn-primary' value='{{ inset }}' />
    </form>
</div>

{% endblock content %}

src/blogproject/templates/post_detail.html
{% extends "base.html" %}

{% block content %}

<div class='col-sm-6 col-sm-offset-3'>

    {% if instance.image %}
    <img src='{{ instance.image.url }}' class='img-responsive' />
    {% endif %}

    <h1>{{ title }}</h1>

    <p>Author: {{ instance.user.first_name }}</p>
<hr>
<p>{{ instance.content }}</p>
<hr>
<a href="{% url 'posts:like' instance.id %}" class="btn btn-info" value="like">Likes: {{ count_likes }}</a>
</div>


    <div class='col-sm-6 col-sm-offset-3'>
    <p class="lead">Comments</p>
    <hr>
    {% for comment in queryset %}
    <blockquote>
        {{ comment.content }}
        <footer>{{ comment.user }} | {{ comment.timestamp|timesince }} ago</footer>
    </blockquote>
    <hr>
    {% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if queryset.has_previous %}
            <a href="?page={{ queryset.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ queryset.number }} of {{ queryset.paginator.num_pages }}.
        </span>

        {% if queryset.has_next %}
            <a href="?page={{ queryset.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
    
    <br>

    <form method="POST" action=".">{% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="Add" class="btn btn-info">
    </form>

    </div>




{% endblock content %}

src/blogproject/templates/post_form.html
{% extends "base.html" %}

{% block content %}

<div class='col-sm-6 col-sm-offset-3'>
    <h1>Form</h1>
    <hr/>

    <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
        <p>{{ form.as_p}}</p>
        <input type='submit' class='btn btn-primary' value='{{ inset }} Post' />
    </form>
</div>

{% endblock content %}

src/blogproject/templates/post_list.html
{% extends "base.html" %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
    {% for obj in object_list %}
    <div class="row">
        <div class="col-sm-12">
            <div class="thumbnail">

            {% if obj.image %}
                <a href="{{ obj.get_absolute_url }}">
                <img src='{{ obj.image.url }}' class='img-responsive' /></a>
            {% endif %}

                <div class="caption post-detail-item">
                    <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.timestamp }}</small></h3>
                    <p>Author: {{ obj.user.first_name }}, country: {{ obj.user.country }}, city: {{ obj.user.city }}</p>
                    <p>Browse content: {{ obj.content|truncatechars:10 }}</p>
                    <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
                </div>

            </div>
        </div><hr/>
    </div>
    {% endfor %}

    <div class="pagination">

        <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}

        </span>

    </div>
</div>

{% endblock content %}